language: php

matrix:
  fast_finish: true
  include:
    - env: DM=~6.0
      php: 7.1
    - env: DM=@dev
      php: 5.5
    - env: DM=~5.0
      php: 5.6
    - env: DM=~4.2
      php: 7
    - env: DM=~4.2
      php: hhvm
  allow_failures:
    - env: DM=@dev

sudo: false

install: travis_retry composer require "wikibase/data-model=$DM" --prefer-source

script: composer ci

after_success:
  - if [[ "`phpenv version-name`" != "7.1" ]]; then exit 0; fi
  - vendor/bin/phpunit --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

cache:
  directories:
    - $HOME/.composer/cache
