language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  fast_finish: true
  include:
    - env: DM=~6.0
      php: 7.1
    - env: DM=@dev
      php: 5.5
    - env: DM=~5.0
      php: 5.6
    - env: DM=~4.2
      php: 7
    - env: DM=~4.2
      php: hhvm
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - env: DM=@dev

sudo: false

before_script:
  - travis_retry composer require "wikibase/data-model=$DM" --prefer-source

script: composer ci

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

cache:
  directories:
    - $HOME/.composer/cache
